image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: "3.20.3"

# -- The [concurrencyPolicy](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy) for the CronJob
concurrencyPolicy: "Allow"

# -- The number of successful finished jobs to retain.
successfulJobsHistoryLimit: ~

# -- The number of failed finished jobs to retain.
failedJobsHistoryLimit: ~

# -- schedule for the cronjob.
schedule: "17 3 * * *"

# -- if the job should be suspended
suspend: false

# -- if the Job should restart when the command fails
restartPolicy: OnFailure

# -- initContainers to use. Requires a list of valid container specs.
initContainers: []

# -- pull secrets for the specified image
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true

  # -- Annotations to add to the service account
  annotations: {}

  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# -- the command or binary to run
command: []

# -- arguments to pass to the command or binary being run
args: []

# -- extra labels applied to all resources
commonLabels: {}

# -- Directly set envFrom config
envFrom: []

# -- Directly set environment variables
env: []

# -- Set environment variables from configMaps or Secrets
envValueFrom: {}

additionalVolumeMounts: []

additionalVolumes: []

labels: {}

annotations: {}

configMap:
  # -- If a ConfigMap with configurable values should be created
  enabled: false

  # -- The data for the ConfigMap. Both keys and values need to be strings.
  data: {}

  # -- If specified, the ConfigMap is mounted as a directory at this path
  mountPath: ""

  # -- Set the `defaultMode` for the files in the directory.
  defaultMode: null

  # -- Mounting of individual keys in the ConfigMap as files
  mountFiles: []
    # - subPath: "config.yml"
    #   mountPath: /app/config.yml

persistence:
  enabled: false

  # -- Where the persistent volume is mounted
  mountPath: /data

  # -- the amount of space to require for the volume
  storage: 1Gi

  # -- Set a storageClassName, otherwise the default class is used.
  storageClassName: ~

  # -- To use an existing PersistentVolume resource, set its name here
  existingVolume: ""

# -- requests and limits for the container
resources: {}

# -- nodeSelector object for the pod
nodeSelector: {}

# -- List of tolerations for the pod
tolerations: []

# -- affinity object for the pod
affinity: {}

# -- Configuration for access to the Kubernetes API
apiAccess:

  # -- DEPRECATED, this is automatically detected by checking if `roleRules` or `clusterRoleRules` are configured. If only `rules` are set, this can be set to false to prevent deployment of the Role and RoleBinding (backwards compatibility).
  enabled: false

  # -- DEPRECATED, use roleRules. Rules for the API access of the ServiceAccount used by the CronJob pods. Check [the documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole) for more information
  rules: []

  # -- Rules for the Role the the pods are bound to. Check [the documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole) for more information
  roleRules: []

  # -- Rules for the ClusterRole the the pods are bound to. Check [the documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole) for more information
  clusterRoleRules: []

# -- [Host Aliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#adding-additional-entries-with-hostaliases)
hostAliases: []
