ci:
  autofix_commit_msg: |
    chore: autofixes from pre-commit

  autoupdate_commit_msg: "chore(deps): update pre-commit dependencies"
  # We use renovate for this anyway
  autoupdate_schedule: quarterly

default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.3
    hooks:
      - id: helm-docs-built
        additional_dependencies: ["github.com/norwoodj/helm-docs/cmd/helm-docs"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.8.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  # Explicitly not using the renovate upstream hook because for some reason installing it is
  # excruciatingly slow (> 10 minutes in some cases)
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-renovate
