ci:
  autofix_commit_msg: |
    chore: autofixes from pre-commit

  autoupdate_commit_msg: "chore(deps): update pre-commit dependencies"
  # We use renovate for this anyway
  autoupdate_schedule: quarterly

default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs-built
        additional_dependencies: ["github.com/norwoodj/helm-docs/cmd/helm-docs"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
