ci:
  autofix_commit_msg: |
    chore: autofixes from pre-commit

  autoupdate_commit_msg: "chore(deps): update pre-commit dependencies"
  # We use renovate for this anyway
  autoupdate_schedule: quarterly

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs-built
        additional_dependencies: ["github.com/norwoodj/helm-docs/cmd/helm-docs"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.121.4
    hooks:
      - id: renovate-config-validator

  - repo: local
    hooks:
      - id: helm unittest
        name: Run helm unittests
        language: script
        pass_filenames: false
        entry: ./ci/helm-unittest
        files: ^charts/.*
