labels:
  # This is here to verify that we're correctly adding newlines everywhere
  some-private-label: some-interesting-value

# Regression test for https://github.com/community-tooling/charts/issues/246
image:
  tag: 1.26.0@sha256:ba9587717b056e1993b051f71cea30ddd5caf09ae2087b1eeb11329f52468e49

# Enable hooks to verify the default config is valid
hooks:
  enabled: true
  jobs:
    pre-upgrade:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "0"
        helm.sh/hook-delete-policy: before-hook-creation

      image:
        repository: alpine
        pullPolicy: IfNotPresent
        tag: latest

      command:
        - echo
      args:
        - Hook executed!

      # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for the hook pod
      resources: {}
