route:
  main:
    enabled: true
    parentRefs:
      - name: my-gateway
        namespace: infra
    hostnames:
      - hello.example.com
    matches:
      - path:
          type: PathPrefix
          value: /
  redirect:
    enabled: true
    parentRefs:
      - name: my-gateway
        namespace: infra
    hostnames:
      - hello.example.com
    httpsRedirect: true
