concurrencyPolicy: Forbid

commonLabels:
  testlabel.tld/owner: ci

envFrom:
  - configMapRef:
      name: test-config

hostAliases:
  - ip: "127.0.0.1"
    hostnames:
      - "foo.local"
      - "bar.local"

apiAccess:
  # This is ignored since roleRules are set
  enabled: false

  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list"]

  roleRules:
    - apiGroups: [""]
      resources: ["deployments"]
      verbs: ["get", "list"]

  clusterRoleRules:
    - apiGroups: [""]
      resources: ["replicasets"]
      verbs: ["get", "list"]
