apiVersion: v2
name: hcloud-csi-driver
description: Deploys the hcloud-csi-driver

home: https://github.com/morremeyer/charts
sources:
  - https://github.com/hetznercloud/csi-driver

type: application

version: 3.0.0
appVersion: 2.5.1

maintainers:
  - name: morremeyer
  - name: ekeih

deprecated: true
