#!/usr/bin/env bash

echo "Creating ConfigMap test-config"
kubectl create configmap test-config
echo "Applying Gateway-API CRDs"
kubectl apply -k https://github.com/kubernetes-sigs/gateway-api/config/crd
