name: "pre-commit"

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Use the token with push permissions if a maintainer works in the repo directly
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        if: github.event.pull_request.head.repo.full_name == 'community-tooling/charts'
        with:
          token: ${{ secrets.BOT_CHART_UPDATE_TOKEN }}
          ref: ${{ github.head_ref }}

      # Use the default config for all forks
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        if: github.event.pull_request.head.repo.full_name != 'community-tooling/charts'

      - name: Setup for pre-commit
        run: pip install pre-commit

      - name: Install dependencies
        run: make install

      - name: Install pre-commit hooks
        # Ensure all hooks are installed so that the following pre-commit run step only measures
        # the time for the actual pre-commit run.
        run: pre-commit install-hooks

      - name: Run pre-commit
        run: pre-commit run --verbose --show-diff-on-failure --color=always --all-files

      - name: Commit linted files
        if: ${{ failure() && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'community-tooling/charts' }}
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "chore(pre-commit): linting"
          author_name: Community Tooling Bot
          author_email: community-tooling@maurice-meyer.de
